
/*
 * Copyright 2021 ElectroOptical Innovations, LLC
 * TestInputRegisterMappedDataStore.h
 * Autogenerated file: 2021-01-05T13:49:43.037074
 */

#pragma once

#include <ArrayView/ArrayView.h>
#include <DataStores/DataStores.h>
#include <Utilities/TypeConversion.h>

#include <algorithm>
#include <array>
#include <cstdint>

struct InputRegisters {
  uint8_t str20[20]{};
  uint8_t str[4]{};
  uint32_t int16{};
  uint32_t int32{};
  uint64_t int641{};
  uint64_t int642{};
  uint64_t int643{};
  uint64_t int644{};
  uint64_t int645{};
  uint64_t int646{};
  uint64_t int647{};
  uint64_t int648{};
  uint64_t int649{};
  uint64_t int640{};
  uint64_t int6411{};
  uint64_t int6412{};
  uint64_t int6413{};
  uint64_t int6422{};
};

enum class InputRegistersEntryIdentifier {
  str20,
  str,
  int16,
  int32,
  int641,
  int642,
  int643,
  int644,
  int645,
  int646,
  int647,
  int648,
  int649,
  int640,
  int6411,
  int6412,
  int6413,
  int6422,
  unknown
};

class InputRegistersWrapper {
 public:
  static const constexpr std::size_t entries_ = 18;
  static const constexpr std::array<
      DataStores::StructEntry<InputRegistersEntryIdentifier>, entries_>
      entry_positions_{
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::str20,
              offsetof(InputRegisters, str20), sizeof(InputRegisters::str20)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::str, offsetof(InputRegisters, str),
              sizeof(InputRegisters::str)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int16,
              offsetof(InputRegisters, int16), sizeof(InputRegisters::int16)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int32,
              offsetof(InputRegisters, int32), sizeof(InputRegisters::int32)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int641,
              offsetof(InputRegisters, int641), sizeof(InputRegisters::int641)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int642,
              offsetof(InputRegisters, int642), sizeof(InputRegisters::int642)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int643,
              offsetof(InputRegisters, int643), sizeof(InputRegisters::int643)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int644,
              offsetof(InputRegisters, int644), sizeof(InputRegisters::int644)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int645,
              offsetof(InputRegisters, int645), sizeof(InputRegisters::int645)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int646,
              offsetof(InputRegisters, int646), sizeof(InputRegisters::int646)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int647,
              offsetof(InputRegisters, int647), sizeof(InputRegisters::int647)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int648,
              offsetof(InputRegisters, int648), sizeof(InputRegisters::int648)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int649,
              offsetof(InputRegisters, int649), sizeof(InputRegisters::int649)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int640,
              offsetof(InputRegisters, int640), sizeof(InputRegisters::int640)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int6411,
              offsetof(InputRegisters, int6411),
              sizeof(InputRegisters::int6411)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int6412,
              offsetof(InputRegisters, int6412),
              sizeof(InputRegisters::int6412)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int6413,
              offsetof(InputRegisters, int6413),
              sizeof(InputRegisters::int6413)},
          DataStores::StructEntry<InputRegistersEntryIdentifier>{
              InputRegistersEntryIdentifier::int6422,
              offsetof(InputRegisters, int6422),
              sizeof(InputRegisters::int6422)},
      };

 private:
  InputRegisters* data_bank_{};

 public:
  explicit InputRegistersWrapper(InputRegisters* data_bank)
      : data_bank_{data_bank} {}
  static const constexpr std::size_t size() { return sizeof(InputRegisters); }

  void SetField(const std::size_t index, const uint8_t* data,
                const std::size_t size) {
    const InputRegistersEntryIdentifier identifier =
        static_cast<InputRegistersEntryIdentifier>(index);
    switch (identifier) {
      case (InputRegistersEntryIdentifier::unknown): {
        // Ignore this case, should be scrubed
        break;
      }
      case (InputRegistersEntryIdentifier::str20): {
        for (std::size_t i = 0; i < std::min(sizeof(data_bank_->str20), size);
             i++) {
          data_bank_->str20[i] = data[i];
        }

        break;
      }
      case (InputRegistersEntryIdentifier::str): {
        for (std::size_t i = 0; i < std::min(sizeof(data_bank_->str), size);
             i++) {
          data_bank_->str[i] = data[i];
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int16): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint32_t, uint8_t>(data,
                                                                        size);
        data_bank_->int16 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int32): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint32_t, uint8_t>(data,
                                                                        size);
        data_bank_->int32 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int641): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int641 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int642): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int642 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int643): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int643 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int644): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int644 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int645): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int645 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int646): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int646 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int647): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int647 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int648): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int648 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int649): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int649 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int640): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int640 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int6411): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int6411 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int6412): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int6412 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int6413): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int6413 = value;

        break;
      }
      case (InputRegistersEntryIdentifier::int6422): {
        const auto value =
            Utilities::Make_MSB_IntegerTypeFromArray<uint64_t, uint8_t>(data,
                                                                        size);
        data_bank_->int6422 = value;

        break;
      }
      default:
        break;
    }
  }

  void GetField(const std::size_t index, uint8_t* data,
                const std::size_t size) const {
    const InputRegistersEntryIdentifier identifier =
        static_cast<InputRegistersEntryIdentifier>(index);
    switch (identifier) {
      case (InputRegistersEntryIdentifier::unknown): {
        // Ignore this case, should be scrubed
        break;
      }
      case (InputRegistersEntryIdentifier::str20): {
        for (std::size_t i = 0; i < std::min(sizeof(data_bank_->str20), size);
             i++) {
          data[i] = data_bank_->str20[i];
        }

        break;
      }
      case (InputRegistersEntryIdentifier::str): {
        for (std::size_t i = 0; i < std::min(sizeof(data_bank_->str), size);
             i++) {
          data[i] = data_bank_->str[i];
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int16): {
        const auto value = data_bank_->int16;
        const auto array = Utilities::MakeMSBU8Array<uint32_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int32): {
        const auto value = data_bank_->int32;
        const auto array = Utilities::MakeMSBU8Array<uint32_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int641): {
        const auto value = data_bank_->int641;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int642): {
        const auto value = data_bank_->int642;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int643): {
        const auto value = data_bank_->int643;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int644): {
        const auto value = data_bank_->int644;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int645): {
        const auto value = data_bank_->int645;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int646): {
        const auto value = data_bank_->int646;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int647): {
        const auto value = data_bank_->int647;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int648): {
        const auto value = data_bank_->int648;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int649): {
        const auto value = data_bank_->int649;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int640): {
        const auto value = data_bank_->int640;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int6411): {
        const auto value = data_bank_->int6411;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int6412): {
        const auto value = data_bank_->int6412;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int6413): {
        const auto value = data_bank_->int6413;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      case (InputRegistersEntryIdentifier::int6422): {
        const auto value = data_bank_->int6422;
        const auto array = Utilities::MakeMSBU8Array<uint64_t>(value);
        for (std::size_t i = 0; i < std::min(array.size(), size); i++) {
          data[i] = array.at(i);
        }

        break;
      }
      default:
        break;
    }
  }
  ArrayView<const uint8_t> get_str20(void) const {
    return ArrayView<const uint8_t>{20, data_bank_->str20};
  }
  void set_str20(const uint8_t* const value, std::size_t length) {
    for (std::size_t i = 0; i < length; i++) {
      data_bank_->str20[i] = value[i];
    }
  }
  ArrayView<const uint8_t> get_str(void) const {
    return ArrayView<const uint8_t>{4, data_bank_->str};
  }
  void set_str(const uint8_t* const value, std::size_t length) {
    for (std::size_t i = 0; i < length; i++) {
      data_bank_->str[i] = value[i];
    }
  }
  uint32_t get_int16(void) const { return data_bank_->int16; }
  void set_int16(uint32_t value) { data_bank_->int16 = value; }
  uint32_t get_int32(void) const { return data_bank_->int32; }
  void set_int32(uint32_t value) { data_bank_->int32 = value; }
  uint64_t get_int641(void) const { return data_bank_->int641; }
  void set_int641(uint64_t value) { data_bank_->int641 = value; }
  uint64_t get_int642(void) const { return data_bank_->int642; }
  void set_int642(uint64_t value) { data_bank_->int642 = value; }
  uint64_t get_int643(void) const { return data_bank_->int643; }
  void set_int643(uint64_t value) { data_bank_->int643 = value; }
  uint64_t get_int644(void) const { return data_bank_->int644; }
  void set_int644(uint64_t value) { data_bank_->int644 = value; }
  uint64_t get_int645(void) const { return data_bank_->int645; }
  void set_int645(uint64_t value) { data_bank_->int645 = value; }
  uint64_t get_int646(void) const { return data_bank_->int646; }
  void set_int646(uint64_t value) { data_bank_->int646 = value; }
  uint64_t get_int647(void) const { return data_bank_->int647; }
  void set_int647(uint64_t value) { data_bank_->int647 = value; }
  uint64_t get_int648(void) const { return data_bank_->int648; }
  void set_int648(uint64_t value) { data_bank_->int648 = value; }
  uint64_t get_int649(void) const { return data_bank_->int649; }
  void set_int649(uint64_t value) { data_bank_->int649 = value; }
  uint64_t get_int640(void) const { return data_bank_->int640; }
  void set_int640(uint64_t value) { data_bank_->int640 = value; }
  uint64_t get_int6411(void) const { return data_bank_->int6411; }
  void set_int6411(uint64_t value) { data_bank_->int6411 = value; }
  uint64_t get_int6412(void) const { return data_bank_->int6412; }
  void set_int6412(uint64_t value) { data_bank_->int6412 = value; }
  uint64_t get_int6413(void) const { return data_bank_->int6413; }
  void set_int6413(uint64_t value) { data_bank_->int6413 = value; }
  uint64_t get_int6422(void) const { return data_bank_->int6422; }
  void set_int6422(uint64_t value) { data_bank_->int6422 = value; }
};  // class InputRegistersWrapper