name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v2

    - name: Install requirements
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make python3

    - name: Checkout Submodules
      run: |
        python3 $(pwd)/git_to_https.py .gitmodules
        git submodule update --init
        git submodule foreach --recursive python3 $(pwd)/git_to_https.py
        git submodule update --init

    # Create build directory (out-of-source build)
    - name: Create Build Environment
      run: cmake -E make_directory ${{ runner.workspace }}/build

    # Configure the CMake project
    - name: Configure CMake
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    # Build the project using CMake
    - name: Build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    # Run tests defined by the CMake configuration
    - name: Test
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: ctest -V -C $BUILD_TYPE
